name = "Sumo Theme"
license = "EPL-2.0"
licenselink = "https://www.eclipse.org/legal/epl-2.0/"
description = "Hugo theme for the Eclipse SUMO website"
homepage = "https://eclipse.org/sumo"
min_version = "0.41"

[author]
  name = "Angelo Banse"
  homepage = "https://github.com/angelobanse"