name: Deploy Hugo Site

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo --minify

    - name: Debug Directory
      run: ls -R

    - name: Deploy to Main Branch
      env:
        ACTIONS_DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
      run: |
        # Backup generated files
        mkdir temp
        cp -r public/* temp/

        # Switch to main branch
        git checkout --orphan main
        git reset --hard
        git clean -df

        # Move files to root directory
        cp -r temp/* .
        rm -rf temp

        # Git configuration
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Commit and push changes
        git add .
        git commit -m "Deploy from source branch"
        git push --force origin main
